package com.thindie.simplyweather.presentation

import com.thindie.simplyweather.R

internal val weatherCodeToStringRes = mapOf(
    0 to R.string.weathercode_0,
    1 to R.string.weathercode_1,
    2 to R.string.weathercode_3,
    3 to R.string.weathercode_2,
    45 to R.string.weathercode_45,
    48 to R.string.weathercode_48,
    51 to R.string.weathercode_51,
    53 to R.string.weathercode_53,
    55 to R.string.weathercode_55,
    56 to R.string.weathercode_56,
    57 to R.string.weathercode_57,
    61 to R.string.weathercode_61,
    63 to R.string.weathercode_63,
    65 to R.string.weathercode_65,
    66 to R.string.weathercode_66,
    67 to R.string.weathercode_67,
    71 to R.string.weathercode_71,
    73 to R.string.weathercode_73,
    75 to R.string.weathercode_75,
    77 to R.string.weathercode_77,
    80 to R.string.weathercode_80,
    81 to R.string.weathercode_81,
    82 to R.string.weathercode_82,
    85 to R.string.weathercode_85,
    86 to R.string.weathercode_86,
    95 to R.string.weathercode_95,
    96 to R.string.weathercode_96,
    99 to R.string.weathercode_99,
)

internal val weatherCodeToDrawableRes = mapOf(
    0 to R.drawable.weather_sunny,
    1 to R.drawable.weather_partly_cloudy,
    2 to R.drawable.weather_partly_cloudy,
    3 to R.drawable.weather_partly_rainy,
    45 to R.drawable.weather_fog,
    48 to R.drawable.weather_fog,
    51 to R.drawable.weather_hail,
    53 to R.drawable.weather_hail,
    55 to R.drawable.weather_hail,
    56 to R.drawable.weather_partly_snowy,
    57 to R.drawable.weather_partly_snowy,
    61 to R.drawable.weather_partly_rainy,
    63 to R.drawable.weather_rainy,
    65 to R.drawable.weather_rainy,
    66 to R.drawable.snowflake_melt,
    67 to R.drawable.snowflake_melt,
    71 to R.drawable.weather_partly_snowy,
    73 to R.drawable.weather_snowy,
    75 to R.drawable.weather_snowy_heavy,
    77 to R.drawable.snowflake_alert,
    80 to R.drawable.weather_pouring,
    81 to R.drawable.weather_pouring,
    82 to R.drawable.weather_pouring,
    85 to R.drawable.snowflake_alert,
    86 to R.drawable.snowflake_alert,
    95 to R.drawable.weather_partly_lightning,
    96 to R.drawable.weather_lightning,
    99 to R.drawable.flash_alert_outline,
)

fun weatherIcon(weatherCode: Int) = weatherCodeToDrawableRes.getValue(weatherCode)
fun weatherNotation(weatherCode: Int) = weatherCodeToStringRes.getValue(weatherCode)